const actionTypes = {
  // BANNER TYPE
  SET_BANNER_LIST: "SET_BANNER_LIST",

  // MOVIE TYPE
  SET_MOVIE_LIST: "SET_MOVIE_LIST",

  // CINEMA TYPE
  SET_THEATER_SYSTEM_INFO: "SET_THEATER_SYSTEM_INFO",
  SET_THEATER_SYSTEM_SHOWTIME: "SET_THEATER_SYSTEM_SHOWTIME",
  SET_MOVIE_SHOWTIME_INFO: "SET_MOVIE_SHOWTIME_INFO",

  // AUTH TYPE
  SET_USER_INFO: "SET_USER_INFO",

  // TICKET ROOM TYPE
  SET_TICKET_ROOM_INFO: "SET_TICKET_ROOM_INFO",
  ADD_SEAT: "ADD_SEAT",
  CLEAR_SEATS: "CLEAR_SEATS",
};

export default actionTypes;
