const actionTypes = {
  // BANNER TYPE
  SET_BANNER_LIST: "SET_BANNER_LIST",

  // MOVIE TYPE
  SET_MOVIE_LIST: "SET_MOVIE_LIST",

  // CINEMA TYPE
  SET_THEATER_SYSTEM_INFO: "SET_THEATER_SYSTEM_INFO",
};

export default actionTypes;
